/* facilitatorProfiles-v3-19.js */
/* Wrap everything in an IIFE so we don’t leak variables */
(function (win) {
  // 1. Profile snippets
  win.facilitatorData = {
    Dannie_Brown: '<div class="row"><figure class="col-sm-12 col-md-6"><img src="https://www.elearning.crandallu.ca/pluginfile.php/164475/mod_folder/content/0/Profile%20Picture%20-%20Dannie%20Brown.jpg" alt="Image of your facilitator Dannie Brown" class="img-responsive"></figure><div class="col-sm-12 col-md-6 float-md-start"><p>Hi there!</p><p>As a recently retired educator, I spent more than 43 years helping students realize their dreams. Born and raised in New Brunswick, Canada, I have lived and worked in four Canadian provinces.</p><p>I have been a business educator and administrator in post-secondary education for my entire career. I have four degrees: B.Ed., M.Ed., and an M.B.A. from UNB-Fredericton, and a D.B.A. from Anderson University in Indiana, USA.</p></div><p>I have a heart for business education and have been highly motivated and energized over the last 15 years by the thousands of international students I have taught and from whom I have learned so much. I have travelled to around 15 countries worldwide and am eager to explore even more.</p><p>I have been married for over 45 years. We have three adult children and five grandchildren. I live in Fredericton, NB, as an adjunct faculty member, working remotely for Crandall University. My hobbies include playing the piano, singing, reading, genealogical research, and travelling.</p><p>✉️ <a href="mailto:dannie.brown@crandallu.ca">dannie.brown@crandallu.ca</a></p></div>',
    Brent_Hudson: '<div class="row">                    <figure class="col-sm-12 col-md-6">                        <img src="https://www.elearning.crandallu.ca/pluginfile.php/164475/mod_folder/content/0/Profile%20Picture%20-%20Brent%20Hudson%202.jpg" alt="Image of your facilitator Brent Hudson" class="img-responsive">                    </figure>                    <div class="col-sm-12 col-md-6 float-md-start">                        <p>Hi everyone!</p>                        <p>My name is Brent Hudson and I have been a part-time lecturer in Religious Studies and Worldview Perspectives at Crandall University since 2001 – most recently working in Bachelor of Organizational Management programme. I have two graduate degrees from McMaster University and earned my bachelor’s degree here at Crandall University.                        </p>                        <p>I have worked in the charitable sector leading organizations and managing volunteers through change and conflict for over 30 years.</p>                    </div>                    <p>I have had an interest in human culture and leadership for many years. What a blessing it is for me, in my role as Facilitator at Crandall University, to meet new people with diverse backgrounds and to have engaging discussions which can enrich us as people and provide an opportunity for everyone to experience growth in both knowledge and action.                    </p> <p>✉️ <a href="mailto:brent.hudson@crandallu.ca">brent.hudson@crandallu.ca</a></p> </div>',
    Gui_Loth: '<div class="row">   <figure class="col-sm-12 col-md-6"> <img    src="https://www.elearning.crandallu.ca/pluginfile.php/164475/mod_folder/content/0/Profile%20Picture%20-%20Gui%20Loth.jpg"    alt="Image of your professor Gui Loth" class="img-responsive"> </figure>    <div class="col-sm-12 col-md-6 float-md-start"> <p>Hi there!</p>    <p>My name is Guilherme and I know my name is too hard to pronounce. Therefore, you can call me Gui like in Guitar.</p> <p>Aside from working as the Senior Director of Remote Learning, here at Crandall, and creating this program, I have quite some experience in business management consulting. More specifically I worked with the Government of Brazil consulting SMEs (Small & Medium Enterprises) back when I used to live in my birth country Brazil.    </p>    </div>  <p>I have a Master’s in Management Science, more precisely Operational Research, and have been teaching Business courses for over 5 years.</p>   <p>I love learning and I like having a pantomath approach to it. Things that I have learned about lately were astronomy, futurism, and philosophy.</p>  <p>I live and work from Hamilton, Ontario, where I spend time investing in the most amazing project of my life: my wife and daughter.</p>   <p>✉️ <a href="mailto:gui.loth@crandallu.ca">gui.loth@crandallu.ca</a></p>  </div>',
    Sylvia_Findlay: '<div class="row"> <figure class="col-sm-12 col-md-6"> <img src="https://www.elearning.crandallu.ca/pluginfile.php/164475/mod_folder/content/0/Profile%20Picture%20-%20Sylvia%20Findlay.jpg" alt="Image of your facilitator Sylvia Findlay" class="img-responsive"></figure> <div class="col-sm-12 col-md-6 float-md-start"> <p>Sylvia Findlay holds a PhD in Higher Education Administration from Illinois State University, and her research interest centers on providing solutions to various challenges faced by international students, primarily on developing the intercultural competence of higher education professionals. </p> <p>Addressing educational access issues for refugees from war-torn regions is one of her biggest passions, and she was awarded a NAGAP research grant for ‘Reaching out to graduate students from war-torn regions.</p> </div> <p>In addition to her PhD, Dr. Findlay also holds a Bachelor’s degree from the University of Madras, a Post Graduate Diploma in Economics from York University in the UK,  a Master of Life Sciences from Pondicherry University, and a Master of Business Administration in Management and Marketing from Bradley University.</p> <p>She has over 18 years of experience, including higher education and global commercial marketing. In addition, she has worked and lived in the EU, Asia, and the US, among multicultural and multidisciplinary teams. She has had the privilege of working in a variety of roles including assessment and evaluations, curriculum development and validation, policy strategy analysis, marketing and program leadership at both academia and fortune 500 commercial organizations. </p> <p>Dr. Findlay comes to Crandall from Kentucky, and is eager for God to use her in Moncton, New Brunswick, saying </p> </div>',
  };

  // 2. Helper to drop the chosen profile into any element
  win.showFacilitator = function (id, targetId = 'facilitatorInfo') {
    const target = document.getElementById(targetId);
    if (!target) return;
    target.innerHTML = win.facilitatorData[id] ?? 'Profile not found';
  };
})(window);
